### ISSUE TITLE
Possibly use mermaid markdown to create code based diagrams/flowcharts instead of images?

### ISSUE THREAD

**Issue by luzpaz** [grd/FreePDM#18]
I'm noticing that flowcharts and such are being generated as images. From a Version control point of view it may make more sense to use a code-based markdown language that autogenerates such image. Especially if GitHub supports it right out of the box

https://github.com/mermaid-js/mermaid

**Comment by Jee-Bee** [comment]
Thanks for your comment.
The images are generated from a SysML(Version 1.6) model in [Eclipse Papyrus](https://www.eclipse.org/papyrus/). When i look at the documentation of mermaid some UML model can be generated, but i don't see any reference to SysML.
My main reason for using Papyrus is that the model is closed so if i have a block named _block1_ and i want to use it in other diagrams it reference always to the original block. When renaming that block to _newblock1_ all references still go to the requested model.
I'm quite sure that this is not possible to in the code based diagrams because it are no references.
The only thing i can do (but don't expect to much) is asking on the eclipse forum if there is a method to export as a mermaid diagrams. For the _Block Definition Diagram_ this should be achievable since it has some overlap with a _Class Diagram_ but the _Internal Block Diagram_ or the _Activity Diagram_ i have my doubts.

**Comment by luzpaz** [comment]
Thanks for the elaboration and time. Yea, whatever makes sense. Ideally we could version control changes in diagrams as well but this doesn't always lend itself to practicality.

**Comment by grd** [comment]
Closing this issue.

**Comment by Jee-Bee** [comment]
Created a [Eclipse Forum topic](https://www.eclipse.org/forums/index.php/t/1110954/). The short answer: The idea is good but it isn't implemented soon and help for implementation is welcome!
