### ISSUE TITLE
Create a docker environment for developers/users

### ISSUE THREAD

**Issue by luzpaz** [grd/FreePDM#78]
Create a way to run FreePDM in a docker container

**Comment by grd** [comment]
I agree. Please have a look at this: https://github.com/grd/FreePDM/discussions/75

Docker-compose is very good. But if you want to have a samba server, which is not entirely necessary but can become very handy for easy access of your files, then maintaining that docker-compose should be run with a Makefile or something. That is what I think because the moment when you start using extra users you need to restart it again anyway.

**Comment by grd** [comment]
Done. However I am having some issues. Dunno what.
This is the documentation file: https://github.com/grd/FreePDM/blob/main/ConceptOfDesign/FreePDM_Install/Docker-Compose.md

**Comment by grd** [comment]
Now it is completely done.

**Comment by grd** [comment]
And now it works like a charm. I got rid of the .env file as well.

**Comment by luzpaz** [comment]
Well done! Sorry was not paying attention and distracted by other tasks.
